uxterm -e "echo \"Win+F1=darker screen\"
echo \"Win+F2=brighter screen\"
echo \"Win+F3=toggle audio\"
echo \"Win+F4=toggle bluetooth\"
echo \"Win+F5=toggle clock\"
echo \"Win+F6=toggle network\"
echo \"Win+F7=toggle ntp\"
echo \"Win+F8=toggle remote\"
echo \"Win+F9=toggle keyboard\"
echo \"Win+F10=toggle ntfs\"
echo \"Win+F11=show status\"
echo \"Win+F12=show shortcuts\"
read" &
